baseURL = "https://dannb.org/"
languageCode = "en-gb"
title = "Rhiannon Jones"
theme = "danntheme"
rssLimit = 20
copyright = "2025 Rhiannon Jones. All rights reserved."
googleAnalytics = "G-93Y1XRNTS1"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Rhiannon Jones"
  description = ""

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 1

[[menu.main]]
  name = "Now"
  url = "/now"
  weight = 2

[[menu.main]]
  name = "Articles"
  url = "/blog"
  weight = 3

[[menu.main]]
  name = "Bookshelf"
  url = "/bookshelf"
  weight = 4

[related]
    threshold = 0
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10
